*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2861,8 +2861,7 @@ done
 
 
 
-
-for ac_header in pcap.h pcap-int.h arpa/inet.h fcntl.h netdb.h netinet/in.h stdlib.h string.h sys/ioctl.h sys/socket.h sys/time.h unistd.h
+for ac_header in pcap-int.h arpa/inet.h fcntl.h netdb.h netinet/in.h stdlib.h string.h sys/ioctl.h sys/socket.h sys/time.h unistd.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -2976,23 +2975,23 @@ fi
 done
 
 
-if test "${ac_cv_header__usr_include_pcap_pcap_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for /usr/include/pcap/pcap.h" >&5
-echo $ECHO_N "checking for /usr/include/pcap/pcap.h... $ECHO_C" >&6
-if test "${ac_cv_header__usr_include_pcap_pcap_h+set}" = set; then
+if test "${ac_cv_header_pcap_pcap_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for pcap/pcap.h" >&5
+echo $ECHO_N "checking for pcap/pcap.h... $ECHO_C" >&6
+if test "${ac_cv_header_pcap_pcap_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header__usr_include_pcap_pcap_h" >&5
-echo "${ECHO_T}$ac_cv_header__usr_include_pcap_pcap_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_pcap_pcap_h" >&5
+echo "${ECHO_T}$ac_cv_header_pcap_pcap_h" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking /usr/include/pcap/pcap.h usability" >&5
-echo $ECHO_N "checking /usr/include/pcap/pcap.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking pcap/pcap.h usability" >&5
+echo $ECHO_N "checking pcap/pcap.h usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 $ac_includes_default
-#include </usr/include/pcap/pcap.h>
+#include <pcap/pcap.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -3017,12 +3016,12 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking /usr/include/pcap/pcap.h presence" >&5
-echo $ECHO_N "checking /usr/include/pcap/pcap.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking pcap/pcap.h presence" >&5
+echo $ECHO_N "checking pcap/pcap.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
-#include </usr/include/pcap/pcap.h>
+#include <pcap/pcap.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -3054,30 +3053,30 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc in
   yes:no )
-    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: /usr/include/pcap/pcap.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&2;};;
+    { echo "$as_me:$LINENO: WARNING: pcap/pcap.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: pcap/pcap.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pcap/pcap.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: pcap/pcap.h: proceeding with the preprocessor's result" >&2;};;
   no:yes )
-    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: /usr/include/pcap/pcap.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: /usr/include/pcap/pcap.h: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&2;};;
+    { echo "$as_me:$LINENO: WARNING: pcap/pcap.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: pcap/pcap.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pcap/pcap.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: pcap/pcap.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pcap/pcap.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: pcap/pcap.h: proceeding with the preprocessor's result" >&2;};;
 esac
-echo "$as_me:$LINENO: checking for /usr/include/pcap/pcap.h" >&5
-echo $ECHO_N "checking for /usr/include/pcap/pcap.h... $ECHO_C" >&6
-if test "${ac_cv_header__usr_include_pcap_pcap_h+set}" = set; then
+echo "$as_me:$LINENO: checking for pcap/pcap.h" >&5
+echo $ECHO_N "checking for pcap/pcap.h... $ECHO_C" >&6
+if test "${ac_cv_header_pcap_pcap_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header__usr_include_pcap_pcap_h=$ac_header_preproc
+  ac_cv_header_pcap_pcap_h=$ac_header_preproc
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header__usr_include_pcap_pcap_h" >&5
-echo "${ECHO_T}$ac_cv_header__usr_include_pcap_pcap_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_pcap_pcap_h" >&5
+echo "${ECHO_T}$ac_cv_header_pcap_pcap_h" >&6
 
 fi
-if test $ac_cv_header__usr_include_pcap_pcap_h = yes; then
+if test $ac_cv_header_pcap_pcap_h = yes; then
    INCLS="$INCLS -I/usr/include/pcap"
 fi
 
