*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1207,6 +1207,9 @@ echo "========================"
 
 
 
+INCLS="-I. "
+
+
 ac_config_headers="$ac_config_headers config.h"
 
 
@@ -2309,8 +2312,6 @@ if test $have_pcap = no ; then
 echo "$as_me: WARNING: this os doesn't support pcap library" >&2;}
         { echo "$as_me:$LINENO: WARNING: contact the author reporting what happened." >&5
 echo "$as_me: WARNING: contact the author reporting what happened." >&2;}
-        { echo "$as_me:$LINENO: WARNING: the build can't continue" >&5
-echo "$as_me: WARNING: the build can't continue" >&2;}
         rm -Rf *.cache *.log
         exit
 fi
@@ -2861,8 +2862,7 @@ done
 
 
 
-
-for ac_header in pcap.h pcap/pcap.h pcap-int.h arpa/inet.h fcntl.h netdb.h netinet/in.h stdlib.h string.h sys/ioctl.h sys/socket.h sys/time.h unistd.h
+for ac_header in pcap.h pcap-int.h arpa/inet.h fcntl.h netdb.h netinet/in.h stdlib.h string.h sys/ioctl.h sys/socket.h sys/time.h unistd.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -2974,6 +2974,113 @@ _ACEOF
 fi
 
 done
+
+
+if test "${ac_cv_header__usr_include_pcap_pcap_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for /usr/include/pcap/pcap.h" >&5
+echo $ECHO_N "checking for /usr/include/pcap/pcap.h... $ECHO_C" >&6
+if test "${ac_cv_header__usr_include_pcap_pcap_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__usr_include_pcap_pcap_h" >&5
+echo "${ECHO_T}$ac_cv_header__usr_include_pcap_pcap_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking /usr/include/pcap/pcap.h usability" >&5
+echo $ECHO_N "checking /usr/include/pcap/pcap.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include </usr/include/pcap/pcap.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking /usr/include/pcap/pcap.h presence" >&5
+echo $ECHO_N "checking /usr/include/pcap/pcap.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include </usr/include/pcap/pcap.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: /usr/include/pcap/pcap.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: /usr/include/pcap/pcap.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: /usr/include/pcap/pcap.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /usr/include/pcap/pcap.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for /usr/include/pcap/pcap.h" >&5
+echo $ECHO_N "checking for /usr/include/pcap/pcap.h... $ECHO_C" >&6
+if test "${ac_cv_header__usr_include_pcap_pcap_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header__usr_include_pcap_pcap_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__usr_include_pcap_pcap_h" >&5
+echo "${ECHO_T}$ac_cv_header__usr_include_pcap_pcap_h" >&6
+
+fi
+if test $ac_cv_header__usr_include_pcap_pcap_h = yes; then
+   INCLS="$INCLS -I/usr/include/pcap"
+fi
+
 
 
 # Checks for typedefs, structures, and compiler characteristics.
@@ -4244,6 +4351,7 @@ s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
 s,@APING_DEFS@,$APING_DEFS,;t t
+s,@INCLS@,$INCLS,;t t
 s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
 s,@build_vendor@,$build_vendor,;t t
@@ -4861,6 +4969,7 @@ echo "  compiler   : $CC"
 echo "  CFLAGS     : $CFLAGS"
 echo "  lib        : $LIBS"
 echo "  defs       : $DEFS"
+echo "  include    : $INCLS"
 echo "  prefix     : $prefix"
 echo "  exec_prefix: $exec_prefix"
 echo "  bindir     : $bindir"
