configure.ac minor changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2225,167 +2225,41 @@ test -n "$SHTOOL" || SHTOOL="./shtool"
 
 # Check and set OS specific parameters.
 
-case "$target_os" in
-*linux*)
-    APING_DEFS="-D__USE_NSHACK"
-    ;;
-*freebsd*)
-    APING_DEFS="-D__USE_NSHACK"
-    ;;
-*openbsd*)
-    ;;
-*)
-    { { echo "$as_me:$LINENO: error: $target_os is NOT SUPPORTED YET" >&5
+case "$host_os" in
+#aix4.*)    optimize_def="-O2"
+#           CC=${CC-"xlc_r"}
+#           CPPFLAGS="-D_THREAD_SAFE $CPPFLAGS"
+#bsdi3*)    CC=${CC-"shlicc2"}
+#           optimize_def="-O2"
+#           LIBS="-lipc $LIBS";;
+#bsdi*)     optimize_def="-O2";;
+openbsd*)   optimize_def="-O2"
+            CPPFLAGS="$CPPFLAGS"
+            LIBS="-pthread";;
+freebsd*)   optimize_def="-O2"
+            CPPFLAGS="-D_THREAD_SAFE -D_USE_NSHACK $CPPFLAGS"
+            LIBS="-pthread";;
+hpux*)      CPPFLAGS="-D_REENTRANT $CPPFLAGS";;
+#irix*)     optimize_def="-O2"
+#           CPPFLAGS="-D_SGI_MP_SOURCE $CPPFLAGS";;
+linux*)     optimize_def="-O2"
+            CFLAGS="-D_GNU_SOURCE"
+            CPPFLAGS="-D_REENTRANT -D_USE_NSHACK $CPPFLAGS"
+            LIBS="-pthread";;
+#mpeix*)    CPPFLAGS="-D_POSIX_SOURCE -D_SOCKET_SOURCE $CPPFLAGS"
+#           LIBS="-lsocket -lsvipc $LIBS";;
+#osf*)      CPPFLAGS="-D_REENTRANT $CPPFLAGS";;
+#sco3.2v4*) CC=${CC-"cc -belf"}
+#           LIBS="-lsocket -lnsl_s $LIBS";;
+#sco*)      CC=${CC-"cc -belf"}
+#           LIBS="-lsocket -lnsl $LIBS";;
+solaris*)   CPPFLAGS="-D_REENTRANT -D_PTHREADS $CPPFLAGS";;
+*) 	    { { echo "$as_me:$LINENO: error: $target_os is NOT SUPPORTED YET" >&5
 echo "$as_me: error: $target_os is NOT SUPPORTED YET" >&2;}
-   { (exit 1); exit 1; }; };
-    ;;
+   { (exit 1); exit 1; }; };;
 esac
 
-# checking for ns hack and pthread
-echo "$as_me:$LINENO: checking whether to activate timeout on ns library" >&5
-echo $ECHO_N "checking whether to activate timeout on ns library... $ECHO_C" >&6
-
-if test -z "$APING_DEFS" ; then
-        echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-else
-        echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-fi
-
 # Checks for libraries.
-# Solaris
-
-
-
-echo "$as_me:$LINENO: checking for socket in -lsocket" >&5
-echo $ECHO_N "checking for socket in -lsocket... $ECHO_C" >&6
-if test "${ac_cv_lib_socket_socket+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lsocket  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char socket ();
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-socket ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_socket_socket=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_socket_socket=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_socket_socket" >&5
-echo "${ECHO_T}$ac_cv_lib_socket_socket" >&6
-if test $ac_cv_lib_socket_socket = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSOCKET 1
-_ACEOF
-
-  LIBS="-lsocket $LIBS"
-
-fi
-
-
-echo "$as_me:$LINENO: checking for gethostbyname in -lnsl" >&5
-echo $ECHO_N "checking for gethostbyname in -lnsl... $ECHO_C" >&6
-if test "${ac_cv_lib_nsl_gethostbyname+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lnsl  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char gethostbyname ();
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-gethostbyname ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_nsl_gethostbyname=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_nsl_gethostbyname=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_nsl_gethostbyname" >&5
-echo "${ECHO_T}$ac_cv_lib_nsl_gethostbyname" >&6
-if test $ac_cv_lib_nsl_gethostbyname = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBNSL 1
-_ACEOF
-
-  LIBS="-lnsl $LIBS"
-
-fi
 
 
 echo "$as_me:$LINENO: checking for pcap_open_live in -lpcap" >&5
@@ -2456,134 +2330,12 @@ echo "$as_me: error: this os doesn't support pcap library" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
-echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
-if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lpthread  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char pthread_create ();
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-pthread_create ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_pthread_pthread_create=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_pthread_pthread_create=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
-echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6
-if test $ac_cv_lib_pthread_pthread_create = yes; then
-   have_pthread=yes ; LIBS="-lpthread $LIBS"
-else
-  have_pthread=no
-fi
-
-echo "$as_me:$LINENO: checking for pthread_create in -lc_r" >&5
-echo $ECHO_N "checking for pthread_create in -lc_r... $ECHO_C" >&6
-if test "${ac_cv_lib_c_r_pthread_create+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lc_r  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char pthread_create ();
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-pthread_create ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_c_r_pthread_create=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_c_r_pthread_create=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_c_r_pthread_create" >&5
-echo "${ECHO_T}$ac_cv_lib_c_r_pthread_create" >&6
-if test $ac_cv_lib_c_r_pthread_create = yes; then
-   have_libc_r=yes ;  LIBS="-pthread $LIBS"
-else
-  have_libc_r=no
-fi
-
-if test $have_pthread = no && test $have_libc_r = no ; then
-	rm -Rf *.cache *.log
-        { { echo "$as_me:$LINENO: error: this os doesn't support pthread" >&5
-echo "$as_me: error: this os doesn't support pthread" >&2;}
-   { (exit 1); exit 1; }; }
-fi
+#AC_CHECK_LIB([pthread], [pthread_create], [ have_pthread=yes ; LIBS="-lpthread $LIBS" ], have_pthread=no)
+#AC_CHECK_LIB([c_r],     [pthread_create], [ have_libc_r=yes ;  LIBS="-pthread $LIBS" ], have_libc_r=no)
+#if test $have_pthread = no && test $have_libc_r = no ; then
+#	rm -Rf *.cache *.log
+#        AC_MSG_ERROR([this os doesn't support pthread])
+#fi
 
 # Checks for header files.
 
@@ -5206,9 +4958,7 @@ done
 
 
 
-
 subdirs="$subdirs plugin"
-
 
 ac_config_files="$ac_config_files Makefile"
 
@@ -5766,7 +5516,7 @@ s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
-s,@APING_DEFS@,$APING_DEFS,;t t
+s,@optimize_def@,$optimize_def,;t t
 s,@INCLS@,$INCLS,;t t
 s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
@@ -6386,6 +6136,7 @@ echo ""
 echo "The aping package has been configured with the following options:"
 echo "  compiler   : $CC"
 echo "  CFLAGS     : $CFLAGS"
+echo "  CPPFLAGS   : $CPPFLAGS"
 echo "  lib        : $LIBS"
 echo "  defs       : $DEFS"
 echo "  include    : $INCLS"
